### ISSUE TITLE
Client follow up (via email not sure)

### ISSUE THREAD

**Issue by YaemikoGit** [e-seet/SIT-INF2001-p11-5#4]

**Comment by YaemikoGit** [comment]
Email send on 1st Oct

**Comment by xavttt** [comment]
Client replied on 3rd Oct with following details to our queries:

1.            Requirement 5: Should we display only 3 staff members as mentioned in Requirement 4, or are we showing every staff member’s workload for that particular week across all features?   Only 3 you have to show, but manager can navigate using next button to view all staff members availability and other details


2.            Requirement 11: Are IT administrators permitted to delete both new staff members and managers from the system? Yes


3.            Are there any specific user interface preferences you’d like to incorporate, such as color schemes, fonts or a particular style for the dashboard UI? You guys will decide. I need a professional design and  great user experience


4.            Regarding requirement 4, if only can view up to 3 staff, how to decide which 3 staff? (Could it be changed to view all staff available at this time and place according to the least workload?) You can choose three randomly or give some facility for manager to choose those three.


5.            Regarding requirement 9, is it possible to clarify what exactly is job preferences? (is it the routes? Is it the time of job)  Both – Route as well as shift timing
